Index: frysk-core/common/ChangeLog 2006-11-20  Andrew Cagney  <cagney@redhat.com>
	* Makefile.rules (checked-parameterless-junit-fail): New target;
	check for fail with no parameters; add to check-local.
	(checked-import-junit-framework): Add to check-local.

diff --git a/frysk-common/Makefile.rules b/frysk-common/Makefile.rules
--- a/frysk-common/Makefile.rules
+++ b/frysk-common/Makefile.rules
@@ -550,6 +550,8 @@ clean-classes-dir:
 # habit of silently compiling invalid Java code (garbage in, garbage out),
 # fortunately ECJ rejects it.  The file list can optionally be pruned first.
 
+# This is part of all-local, since, if this fails the build won't fly.
+
 all-local: checked-ecj-compile
 CLEANFILES += checked-ecj-compile
 checked-ecj-compile: files.list $(GEN_DIRNAME).jar
@@ -583,6 +585,9 @@ clean-ecj-dir:
 # Run through the glade files and check to see that they don't contain
 # references to glade libraries.  Create a local catalog so that it
 # doesn't try to down load the XML definition stuff from the internet.
+
+# This is part of all-local, since, if this fails the build won't fly.
+
 all-local: checked-glade-xml
 GLADE_DTD_FILE = file://`$(PKG_CONFIG) --variable=prefix libglade-2.0`/share/xml/libglade/glade-2.0.dtd 
 CLEANFILES += checked-glade-xml
@@ -618,7 +623,7 @@ glade.catalog:
 # directories .jar file as that is updated when ever any java files
 # change.
 
-all-local: checked-import-junit-framework
+check-local: checked-import-junit-framework
 CLEANFILES += checked-import-junit-framework
 checked-import-junit-framework:  $(GEN_DIRNAME).jar
 	if for dir in $(GEN_DIRS) ; do \
@@ -631,6 +636,25 @@ checked-import-junit-framework:  $(GEN_DIRNAME).jar
 		echo 1>&2 "" ; \
 		echo 1>&2 "***** frysk code should use frysk.junit," ; \
 		echo 1>&2 "***** and not junit.framework." ; \
+		echo 1>&2 "" ; \
+		exit 1 ; \
+	fi
+	touch $@
+
+# Check that everything is calling fail() with a parameter.
+
+check-local: checked-parameterless-junit-fail
+CLEANFILES += checked-parameterless-junit-fail
+checked-parameterless-junit-fail: $(GEN_DIRNAME).jar
+	if for dir in $(GEN_DIRS) ; do \
+		find $(srcdir)/$$dir ./$$dir \
+			-type f -name '[a-zA-Z]*.java' -print \
+			-o -name inua -prune \
+			-o -name junit -prune ; \
+	   done | xargs grep -H -n -e 'fail *()' ; \
+	then \
+		echo 1>&2 "" ; \
+		echo 1>&2 "***** frysk tests should paramterize fail()" ; \
 		echo 1>&2 "" ; \
 		exit 1 ; \
 	fi
