Index: frysk-sys/common/ChangeLog 2006-11-14  Andrew Cagney  <cagney@redhat.com>
	* Makefile.rules (checked-import-junit-framework): New.
	(checked-glade-xml): Rename glade.check.
	(checked-ecj-compile): Rename ecj/check.

diff --git a/frysk-common/Makefile.rules b/frysk-common/Makefile.rules
--- a/frysk-common/Makefile.rules
+++ b/frysk-common/Makefile.rules
@@ -551,8 +551,9 @@ clean-classes-dir:
 # habit of silently compiling invalid Java code (garbage in, garbage out),
 # fortunately ECJ rejects it.  The file list can optionally be pruned first.
 
-all-local: ecj/checked
-ecj/checked: files.list $(GEN_DIRNAME).jar
+all-local: checked-ecj-compile
+CLEANFILES += checked-ecj-compile
+checked-ecj-compile: files.list $(GEN_DIRNAME).jar
 	rm -rf ecj
 	mkdir -p ecj
 if HAVE_ECJ
@@ -579,22 +580,14 @@ endif
 clean-local: clean-ecj-dir
 clean-ecj-dir:
 	rm -rf ecj
-
+
 # Run through the glade files and check to see that they don't contain
 # references to glade libraries.  Create a local catalog so that it
 # doesn't try to down load the XML definition stuff from the internet.
-
-all-local: glade.checked
+all-local: checked-glade-xml
 GLADE_DTD_FILE = file://`$(PKG_CONFIG) --variable=prefix libglade-2.0`/share/xml/libglade/glade-2.0.dtd 
-glade.catalog:
-	rm -f $@.tmp
-	$(XMLCATALOG) --noout -v --create $@.tmp
-	$(XMLCATALOG) --noout -v --add rewriteURI \
-		http://glade.gnome.org/glade-2.0.dtd \
-		$(GLADE_DTD_FILE) \
-		$@.tmp
-	mv $@.tmp $@
-glade.checked: $(glade_DATA) glade.catalog
+CLEANFILES += checked-glade-xml
+checked-glade-xml: $(glade_DATA) glade.catalog
 	export SGML_CATALOG_FILES=glade.catalog ; \
 	for f in x $(glade_DATA) ; do \
 		test $$f = x && continue; \
@@ -610,5 +603,30 @@ glade.checked: $(glade_DATA) glade.catalog
 			exit 1; \
 		fi; \
 	done
-	touch glade.checked
-CLEANFILES += glade.checked glade.catalog
+	touch $@
+CLEANFILES += glade.catalog
+glade.catalog:
+	rm -f $@.tmp
+	$(XMLCATALOG) --noout -v --create $@.tmp
+	$(XMLCATALOG) --noout -v --add rewriteURI \
+		http://glade.gnome.org/glade-2.0.dtd \
+		$(GLADE_DTD_FILE) \
+		$@.tmp
+	mv $@.tmp $@
+
+# Check that everything, well except for a few exceptions, is using
+# frysk.junit and not the junit stuff directly.  Depend on the
+# directories .jar file as that is updated when ever any java files
+# change.
+
+all-local: checked-import-junit-framework
+CLEANFILES += checked-import-junit-framework
+checked-import-junit-framework:  $(GEN_DIRNAME).jar
+	for dir in $(GEN_DIRS) ; do \
+		find $(srcdir)/$$dir ./$$dir \
+			-type f -name '[a-zA-Z]*.java' -print \
+			-o -name inua -prune \
+			-o -name junit -prune ; \
+	done | xargs grep -H -n -e 'import *junit\.framework' ; \
+	test $$? != 0 # success is failure
+	touch $@
